id: I74A776EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T16:13:41+00:00'
last_modified: '2022-06-07T12:05:18.157891+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181172
  title: གཡག་ཟེའི་སྐུ་ཆུང་ལྔ་པ་གར་དབང་བསྟན་འཛིན་བཟང་པོའི་གཏེར་ཆོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6880':
      image_group_id: I4CZ74477
      title: Volume 1 of sku 'bum gdan rabs/
      total_pages: 620
      order: 1
      base_file: 6880.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
